import { Inter } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(check) {
  console.log("check--------->", check)
  return (
    <html lang="en">
      <body className={inter.className} id="body">
        <div className="bg-image" style={{ backgroundImage: "url('https://mdbcdn.b-cdn.net/img/Photos/Others/images/76.webp')" }}>
          {check?.children}
        </div>

        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
        <script src="/AdminFiles/lib/chart/chart.min.js"></script>
        <script src="/AdminFiles/lib/easing/easing.min.js"></script>
        <script src="/AdminFiles/lib/waypoints/waypoints.min.js"></script>
        <script src="/AdminFiles/lib/owlcarousel/owl.carousel.min.js"></script>
        <script src="/AdminFiles/lib/tempusdominus/js/moment.min.js"></script>
        <script src="/AdminFiles/lib/tempusdominus/js/moment-timezone.min.js"></script>
        <script src="/AdminFiles/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js"></script>


        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet" />

      </body>
    </html>
  );
}
